api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_items_per_page: 5
        pagination_maximum_items_per_page: 30
        pagination_client_items_per_page: true
    enable_docs: true
    enable_swagger: true
    enable_swagger_ui: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
